### ISSUE TITLE
DB: We need to remove waterGap from bar_charts

### ISSUE THREAD

**Issue by IoannaMi** [Deltares/waterloupe-basin-data#11]
The api endpoint  /api/bar_chart which calls the func.wl.scenariodata_agg_json returns also the values of the waterGap

That is not the desired behavior. 

Suggestion: in the scenariodata_per_data view we need to include only availability and demand parameters.

**Comment by IoannaMi** [comment]
FE:  Fit the legend (e-charts)

**Comment by IoannaMi** [comment]
sub parameter is not filled in the view for water gap

**Comment by wschoonveld** [comment]
add:  where sub_parameter is not null
